<?php

namespace Mm\RecycleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatterypackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatterypackRepository extends EntityRepository
{

  /**
   * @return array
   */
  public function findAllGroupedByType()
    {
        return $this->getEntityManager()
            ->createQuery(
              'SELECT b.type, SUM(b.count) as total
              FROM MmRecycleBundle:Batterypack b
              GROUP BY b.type
              '
            )
            ->getResult();
    }

}
