mm_recycle_batterypack_add:
    path:     /batterypack/add
    defaults: { _controller: MmRecycleBundle:Batterypack:add }
mm_recycle_batterypack_index:
    path:     /batterypack/index
    defaults: { _controller: MmRecycleBundle:Batterypack:index }
mm_recycle_batterypack:
    path:     /batterypack
    defaults: { _controller: MmRecycleBundle:Batterypack:index }
mm_recycle_homepage:
    path:     /
    defaults: { _controller: MmRecycleBundle:Batterypack:index }
