parameters:
#    mm_recycle.example.class: Mm\RecycleBundle\Example

services:
#    mm_recycle.example:
#        class: %mm_recycle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
