# src/Mm/RecycleBundle/Resources/config/validation.yml
Mm\RecycleBundle\Entity\Batterypack:
    properties:
        type:
            - NotBlank: ~
        count:
            - NotBlank: ~
        name:
            - Blank: ~